repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ["--maxkb=2000"]

  # Sort package imports alphabetically
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/keewis/blackdoc
  rev: v0.3.8
  hooks:
  - id: blackdoc

  # Formatting with "black" coding style
- repo: https://github.com/psf/black
  rev: 23.10.0
  hooks:
      # Format Python files
  - id: black
      # Format Jupyter Python notebooks
  - id: black-jupyter

  # Remove output from Jupyter notebooks
- repo: https://github.com/aflc/pre-commit-jupyter
  rev: v1.2.1
  hooks:
  - id: jupyter-notebook-cleanup
    args: ["--remove-kernel-metadata"]
